### ISSUE TITLE
Error pages partially misstyled

### ISSUE THREAD

**Issue by 3-io** [catppuccin/youtube#11]
## Issue
When a user hits an error page, either YouTube styled, or Google styled, various elements are misstyled, or have image aliasing issues.

- YouTube type not found error pages have black text with white drop shadow
- YouTube type internal error pages are missing most styles
- Google type error pages have black text and aliasing issues on the broken robot PNG

### Consent subdomain [error page](https://consent.youtube.com/m) (Google styled)
![image](https://user-images.githubusercontent.com/89976687/190679635-fcbca7f8-35ed-4da6-bbc1-32747b9b9389.png)

### Channel [error page](https://www.youtube.com/c/totally-not-a-real-channel) (YouTube not found styled)
![image](https://user-images.githubusercontent.com/89976687/190679834-6d2c3ce7-6214-4f06-8478-fa3dc1aed7ba.png)

### Internal [error page](https://www.youtube.com/live_chat) (YouTube internal error styled)
![image](https://user-images.githubusercontent.com/89976687/190681164-03bcdbe8-bd16-4cb6-8316-8985ab8ea984.png)

**Comment by isabelroses** [comment]
The internal error page is styled in a way that would make it impossible to change without affecting anything else. However, with the [PR](https://github.com/catppuccin/youtube/pull/37), it should fix both the fix both the consent subdomain (by removing styling there completely - to prevent site leaking) and the channel error page should be completely changed and fixed.
