### ISSUE TITLE
Video hover button not properly themed

### ISSUE THREAD

**Issue by AnubisNekhet** [catppuccin/youtube#13]
These buttons are not colored properly:
<img width="355" alt="image" src="https://user-images.githubusercontent.com/102488279/193563836-da3f1674-0978-488d-bcf4-54814376ff4f.png">
If we add `background-color: var(--hover-background);` to `.ytd-video-preview ytd-toggle-button-renderer #button.ytd-toggle-button-renderer`, it resolves itself.
<img width="349" alt="image" src="https://user-images.githubusercontent.com/102488279/193563798-4f14c093-d7f0-44b3-9c35-7c3c7a0ab983.png">

**Comment by elkrien** [comment]
Should be fixed now in version 1.3.5 - thx
