### ISSUE TITLE
Ambient Mode shows original background

### ISSUE THREAD

**Issue by miyucomics** [catppuccin/youtube#17]
As you can see in the screenshot below, ambient mode breaks the theme and shows the original background color.
![image](https://user-images.githubusercontent.com/72044529/198904239-5612f9e6-ed84-4178-8f7c-feeb92c6c827.png)

**Comment by alba4k** [comment]
Yup, I'm also hoping that this will get fixed soon. The redesign of youtube is fairly recent, so it's to be expected that this won't be fixed on day one

**Comment by satr14washere** [comment]
I have the same problem

**Comment by scattagain** [comment]
Hopefully it is fixed in the coming months :crossed_fingers:

**Comment by alba4k** [comment]
uhm

**Comment by satr14washere** [comment]
So in youtube you can disable ambient mode

**Comment by isabelroses** [comment]
I can't actually test this feature as I don't have ambient mode yet
![image](https://user-images.githubusercontent.com/71222764/223447288-17dc117b-cce2-4d35-af38-5b5c8f49a204.png)
So recommended temporary fix: disable ambient mode

**Comment by alba4k** [comment]
funfact, this is not an issue anymore, as cinematic mode simply _does not work_ anymore when using this theme.

![immagine](https://user-images.githubusercontent.com/84153269/224161568-e0f869c8-b2aa-458a-a7fb-bafe52522fd9.png)

**Comment by isabelroses** [comment]
@alba4k well that is quite interesting. I hope things stay that way, but until I can actually make any changes or they remove the feature I guess this issue has to stay.
