### ISSUE TITLE
Latest version will not load.

### ISSUE THREAD

**Issue by CaidenBlock** [catppuccin/youtube#27]
https://github.com/catppuccin/youtube/commit/2f551152678304d260e30aab0dcbb907aa0be334 is a breaking change, seemingly due to 2 extra spaces at the start of a few dozen lines

https://github.com/catppuccin/youtube/blob/009b7a1778ebbbd365d15e2cf9b2b9075e9705f1/src/YouTubeCatppuccinMocha.user.css#L330
https://github.com/catppuccin/youtube/blob/009b7a1778ebbbd365d15e2cf9b2b9075e9705f1/src/YouTubeCatppuccinMocha.user.css#L872
https://github.com/catppuccin/youtube/blob/009b7a1778ebbbd365d15e2cf9b2b9075e9705f1/src/YouTubeCatppuccinMocha.user.css#L1094

edit: Seems to have caused indenting problems all over.

**Comment by elkrien** [comment]
should be corrected now
