### ISSUE TITLE
Style leaking to other websites

### ISSUE THREAD

**Issue by justTOBBI** [catppuccin/youtube#29]
It appears as if the style is leaking onto other websites as well.
Could be a RegEx Issue.

**Comment by backwardspy** [comment]
i believe this is the same problem as we found on the github theme; [this rule](https://github.com/catppuccin/youtube/blob/14bbed9f45dc38b955d170be60eae87d936abafe/src/YouTubeCatppuccinMocha.user.css#L4282-L4285) is outside of the regex block.

**Comment by justTOBBI** [comment]
I'll PR the change
