### ISSUE TITLE
inccorrect logo color

### ISSUE THREAD

**Issue by Dandraghas** [catppuccin/youtube#32]
### Bug:
logo of youtube in top left is incorrect:
![image](https://user-images.githubusercontent.com/91272905/221419747-7642a7bb-0a9f-431a-80c1-bbe7735e821a.png)
however if i go to some video and open side bar logo looks correct:
![image](https://user-images.githubusercontent.com/91272905/221419874-3ee47e55-8725-4cb4-a503-fd5acc54ec7e.png)

### Additional Information
tested on mocha style

**Comment by 3-io** [comment]
Have noticed this for a week or two - I assumed it was due to Youtube rolling out a short-lived logo variation. It appears to no longer be the case for the Basic and Premium logo.
