### ISSUE TITLE
Keyboard accesibilty control not fully styled in dark mode

### ISSUE THREAD

**Issue by 3-io** [catppuccin/youtube#34]
When hitting tab 3 times from landing on a page, a hidden element appears to assist with screen readers. While this displays correctly on light mode, it is illegible on dark mode

Light mode:
![image](https://user-images.githubusercontent.com/89976687/222435662-265f2140-c8ba-4996-87cc-944266aa5177.png)

Dark mode:
![image](https://user-images.githubusercontent.com/89976687/222435772-61b00eeb-2baa-4104-9de3-6f2a8d6d477d.png)

**Comment by isabelroses** [comment]
Default youtube has this broken too: 
![image](https://user-images.githubusercontent.com/71222764/223435655-e55d7ce1-3b12-4309-93b1-a35924114ea3.png)
Also when using the YouTube port the user should be in youtube's built in light mode.
Link to install guide: https://github.com/catppuccin/youtube
