### ISSUE TITLE
Alternative install links don't work.

### ISSUE THREAD

**Issue by vunhatchuong** [catppuccin/youtube#48]
Alternative install links for each version doesn't work.

**Comment by rubyowo** [comment]
for the time being you can use these:
- [Latte](https://raw.githubusercontent.com/catppuccin/youtube/3c95e48d97ae95dd4c408086204b332526cfad18/src/YouTubeCatppuccinLatte.user.css)
- [Frappe](https://raw.githubusercontent.com/catppuccin/youtube/3c95e48d97ae95dd4c408086204b332526cfad18/src/YouTubeCatppuccinFrappe.user.css)
- [Macchiato](https://raw.githubusercontent.com/catppuccin/youtube/3c95e48d97ae95dd4c408086204b332526cfad18/src/YouTubeCatppuccinMacchiato.user.css)
- [Mocha](https://raw.githubusercontent.com/catppuccin/youtube/3c95e48d97ae95dd4c408086204b332526cfad18/src/YouTubeCatppuccinMocha.user.css)

**Comment by isabelroses** [comment]
V2.1.0 Is now pushed replacing the alternate installs.
