### ISSUE TITLE
Black bars not black anymore

### ISSUE THREAD

**Issue by alba4k** [catppuccin/youtube#49]
The black bars that show when the aspect ratio from a video differs from the one shown by the display are currently the same color as the youtube background, instead of just being black.

This wasn't an issue until some weeks ago (I recently updated the theme).

![immagine](https://user-images.githubusercontent.com/84153269/225411854-0bc0f189-adcb-4527-bab3-498a57a00650.png)

Here shown with the mocha theme

**Comment by isabelroses** [comment]
Try 
![image](https://user-images.githubusercontent.com/71222764/225421546-8ff71192-6ce2-4085-a57c-92ec59be489e.png)
This is added in version V2.1.0 In case your not on that version
