### ISSUE TITLE
Youtube logo question

### ISSUE THREAD

**Issue by Dandraghas** [catppuccin/youtube#50]
so does this logo is correct?
![image](https://user-images.githubusercontent.com/91272905/225640851-0384d9bb-dbc3-41a2-b2bc-78d3431a2db3.png)

maybe its not right color because in readme file of this repository it was red

i using mocha theme

**Comment by rubyowo** [comment]
the logo color is changed by your chosen accent. Also, in newer versions, the play button is black. Please update.
