### ISSUE TITLE
Premium logo not displayed correctly

### ISSUE THREAD

**Issue by ooonea** [catppuccin/youtube#59]
I installed following the guide, but whatever accent I choose, the premium logi is not displayed correctly, the r is missing.

<img width="960" alt="Screenshot 2023-05-28 191105" src="https://github.com/catppuccin/youtube/assets/35407790/c78c0474-ae69-4462-9dc2-d76616309eeb">

**Comment by isabelroses** [comment]
fixed in: https://github.com/catppuccin/youtube/commit/521f8dcb8ec8507ad2e485294fc061a411a9fc0f
