### ISSUE TITLE
Text inside "Join" button text is light (white) instead of dark (black)

### ISSUE THREAD

**Issue by sukinoverse** [catppuccin/youtube#6]
## Overview
- I believe that text inside the button should be dark?

## Screenshots
![Screenshot 2022-07-30 at 11-06-29 (1) spin9 - YouTube](https://user-images.githubusercontent.com/9070844/181871811-b1293d4d-53a4-400e-9c2c-0fb92953c8c2.png)

![Screenshot 2022-07-30 at 11-09-40 (1) spin9 รีวิว Sony Bravia XR OLED A80K — รุ่นท็อป เด่นทั้งภาพและเสียง - YouTube](https://user-images.githubusercontent.com/9070844/181871881-a961f05c-f75f-4871-984c-034ab592feae.png)

**Comment by elkrien** [comment]
fixed - should be working in 1.3.1 version correctly
