### ISSUE TITLE
Mocha has wrong text color on "reply" and "view x replies" button.

### ISSUE THREAD

**Issue by sukinoverse** [catppuccin/youtube#7]
## What happened?
Catppuccin Theme - Mocha has wrong text color on "reply" and "view x replies" button.
The button text should be light instead of dark color.

## Screenshots
<img width="1440" alt="Screen Shot 2022-08-01 at 22 30 46" src="https://user-images.githubusercontent.com/9070844/182186149-3e0c6915-17c9-45ca-b4f1-c81d4e6abdb7.png">

**Comment by elkrien** [comment]
fixed in 1.3.2
