### ISSUE TITLE
Background in the fullscreen mode should be always black

### ISSUE THREAD

**Issue by andreiborisov** [catppuccin/youtube#9]
It's distracting when the background of a video has a color, we probably want it to be always black for all Catppuccin theme variants:

![CleanShot 2022-09-14 at 19 08 27 2@2x](https://user-images.githubusercontent.com/13354491/190193180-d33574f9-2b30-4731-8a51-9e84e0a2c96b.png)

**Comment by elkrien** [comment]
Should be fixed now - it was introduced in last commit and I agree that it doesn't look good.

**Comment by andreiborisov** [comment]
Thank you for the quick fix and a great theme 🙏🏻
